### ISSUE TITLE
[bug] freeze on Nvidia because VLC VDPAU bugs

### ISSUE THREAD

**Issue by danilw** [jeffshee/hidamari#11]
I think its only Nvidia bug because VLC

On starting video with vdpau it works(displayed on Gnome desktop)
![1](https://user-images.githubusercontent.com/24825887/114100676-53686400-98cd-11eb-9ad2-bd3039d344fb.png)
but **right-click on Desktop to call hidamari menu - Gnome freeze or becomes unresponsive** and hidamari python process has 100% CPU usage, Gnome back to work after killing hidamari from terminal(ctrl-alt-f1).

console spam with the same error (or all those errors saved to logs its gigabytes of log per minute):
![1](https://user-images.githubusercontent.com/24825887/114098330-e1425000-98c9-11eb-9c96-329fef4c118a.png)

to disable this spam - add to `src/hidamari` to line 16 before calling Player

```
os.environ["VLC_VERBOSE"] = str("-1")
```

removing line 62-63 from `src/player.py` these two lines

```
        # x11 = ctypes.cdll.LoadLibrary('libX11.so')
        # x11.XInitThreads()
```
make right-click menu work

thanks for the amazing tool hidamari, that allow set live wallpaper on Gnome 3

**Comment by 94824** [comment]
You can always trust Nvidia to screw things up :)

Is this under wayland or in X? 

Also, while I'm glad that disabling those two lines fixes the issue, it also disables hardware acceleration--which means that it's going to only render on the CPU, so I'm not so sure it's a very long term solution--especially because VLC is used *for* it's hardware accleration.

**Comment by danilw** [comment]
> You can always trust Nvidia to screw things up :)

Nvidia or VLC, other ffmpeg-based "surface" in apps like mpv or other apps does work without right click bug. VLC(app) also does not allow right-click(it flash for one frame and become hidden) in Linux if used VDPAU and it freezes on fullscreen if I right-click... so it similar.

> Is this under wayland or in X?

I'm in OpenSuse and X11

as I know Nvidia does not support Wayland, only in next drivers big update 470 they will add Wayland support, current latest driver version is 460

> so I'm not so sure it's a very long term solution--especially because VLC is used for it's hardware acceleration.

you can just add a warning on github page and people with Nvidia will find its solution

maybe changing right-click menu event to rightclick-window event(open new window with menu instead of popup menu) may fix it, or changing VLC overlay on something else

**Comment by 94824** [comment]
Yeah, we can certainly leave a warning if this issue is reproducable in other Nvidia systems as well. VLC seems to be the best solution for hardware rendering at the moment, but we're certainly willing to swap the backend assuming all the features still work.

Right clicking to spawn a window could be a good solution, Hidamari already has a Control Panel window, it just doesn't have the the same toggles as the context menu, they're complimentary.

When you mention a tray event, if you mean tray icons like KDE or Windows, that's probably not wise. This program is certainly tailored more towards Gnome, and requiring a tray extension for basic functionality might be a turnoff for some users who would rather have a "Pure Gnome" system. Are you running Hidamari under Gnome, or another DE?

**Comment by danilw** [comment]
Gnome 3.38

I was looking for a way to "display my application on Gnome desktop" and found your solution, I found everything I needed as the example on this your code

> VLC seems to be the best solution for hardware rendering at the moment

to display video In Python (in other my apps) I use `vispy` to create GLFW surface and in GLFW surface I display ffmpeg output using `ffmpeg pipe` output (GLFW display single mesh with shader that getting ffmpeg frames to display) (you can google it easy to setup in python, and I'm almost 100% sure it will work for your this app)

in theory, you can display direct Vulkan output in GLFW from ffmpeg without even copying to RAM... but idk how to setup it in python, may be just overcomplicated and not worth its time...

**I don't want waste your time anymore il close this bugreport, thanks again you save lots of time for me**

**Comment by jeffshee** [comment]
@danilw Hi, thanks for reporting the issue. It is very strange indeed since I mainly develop and test on a PC with an Nvidia card, except everything works fine on my side. So for now, I'm not sure what's causing the issue.

There is some _not too_ similar bug reported on Ubuntu tho (combination of vlc and Nvidia):
https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-435/+bug/1846374

Although we don't know how to fix that yet, perhaps it is a sane thing to limit the vlc log as you described. For instance, an environment variable that controls the log verbosity of Hidamari overall.

FYI, the environment I had tested:
```
OS: Fedora 33
GNOME Version: 3.38.5
Windowing System: X11
Nvidia Card: GTX 1080
Nvidia Driver Version: 460.67
VLC Related Package Version:
vlc-core-3.0.12-1.fc33.x86_64
vlc-3.0.12-1.fc33.x86_64
python3-vlc-3.0.11115-2.fc33.noarch
```
