### ISSUE TITLE
How to launch the program?

### ISSUE THREAD

**Issue by EuCaue** [jeffshee/hidamari#16]
I have installed program, but a not sure how to launch him, don't have any icon in appgrid (DE GNOME) output of "hidamari" in terminal

$ hidamari                                                        
fish: Unknown command: hidamari

**Comment by jeffshee** [comment]
Hi,
Probably there is few issue that you need to handle:
1. `$HOME/bin` directory isn't listed in your `PATH` environment 
This caused `hidamari` isn't recognised as a command. Since you are probably using fish, I think you can solve this by executing
```
set -U fish_user_paths $HOME/bin $fish_user_paths
```
After this, you should be able to call `hidamari` in terminal. Not sure why the icon isn't show up, but I believe it's the same reason.

2. Did you installed all the required python packages?
It is listed in the Prerequisite section. 
```
pip3 install pillow pydbus python-vlc youtube-dl
```
Note that you need sudo to install python package to your system's python. If you did this but it still doesn't work, please comment your `which python3` and `pip3 list` at below. 

BTW which distro are you using?

Thanks!

**Comment by EuCaue** [comment]
> BTW which distro are you using?
Archlinux

> pydbus python-vlc youtube-dl
These dependencies were missing, **_THANKS_**!
