### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'force_update'

### ISSUE THREAD

**Issue by lrtz0** [jeffshee/hidamari#20]
First time using this, and the app didn't start from Unity Dash.
Tried starting it up from the terminal, only to be greeted by:
```
Config JSON:
{'audio_volume': 50,
 'data_source': None,
 'is_detect_maximized': True,
 'is_mute': False,
 'is_static_wallpaper': True,
 'mode': None,
 'static_wallpaper_blur_radius': 5,
 'version': 2}
Mode: Null
Monitor: width 1366 height 1366

(hidamari:26187): Wnck-WARNING **: 18:12:43.989: libwnck is designed to work in X11 only, no valid display found
Traceback (most recent call last):
  File "/usr/bin/hidamari", line 3, in <module>
    server.run()
  File "/usr/share/hidamari/server.py", line 170, in run
    hidamari.dbus_published_callback()
  File "/usr/share/hidamari/server.py", line 48, in null
    self.player = NullPlayer(self.config)
  File "/usr/share/hidamari/null_player.py", line 12, in __init__
    super().__init__(config)
  File "/usr/share/hidamari/base_player.py", line 35, in __init__
    self.window_handler = WindowHandler(self._on_window_state_changed)
  File "/usr/share/hidamari/utils.py", line 104, in __init__
    self.screen.force_update()
AttributeError: 'NoneType' object has no attribute 'force_update'
```
How do I fix this?

**Comment by lrtz0** [comment]
Also, I can see that `libwnck` reports that it's designed to work in X11 only, but I'm using Wayland (Ubuntu 21.04).
Maybe this is the cause?

**Comment by lrtz0** [comment]
Restarted using X11. It almost works. For some reason, when I start playing the video, my desktop icons are hidden behind the video. Is this a known bug, or is it how Hidamari is suppposed to work?

**Comment by jeffshee** [comment]
Hi @lrtz0, thanks for reporting.
Hidamari does work with Wayland (if you are using GNOME), and I think the bug you report now is actually easy to fix.
Could you provide an output of `echo $DESKTOP_SESSION`?

>Restarted using X11. It almost works. For some reason, when I start playing the video, my desktop icons are hidden behind the video. Is this a known bug, or is it how Hidamari is suppposed to work?

Unfortunately, it is how Hidamari supposed to work. You can't see the desktop icons because Hidamari needs to create a window over the desktop. In vanilla GNOME, there is no desktop icon. The desktop icon functionality was actually added by Ubuntu using an extension. If you want to show the desktop icon on top of Hidamari, you will need to restart (disable then enable again) that specific extension. However, you will lose the right-click access to Hidamari's GUI if you do so. (It means this workaround is not that ideally :neutral_face: )

**Comment by nicole-smartb** [comment]
Hello, trying out Hidamari, after found out that Komorebi not working with Wayland (including the fork version: https://github.com/Komorebi-Fork/komorebi). Ran `echo $DESKTOP_SESSION` and the output I'm getting is `ubuntu`.

Is this bug a matter of changing something in the script?

**Comment by jeffshee** [comment]
@nicole-smartb Hi, thanks for reporting. Should be fixed now. Please try the master branch at the moment (manual installation).
