### ISSUE TITLE
Suggestion: scale video to fit multiple monitors

### ISSUE THREAD

**Issue by E-Bachman** [jeffshee/hidamari#3]
**Suggestion**
Add support for scaling video to fit multiple monitors

**Example**
```
display0           display1
1920x1080     1920x1080
Video 1           Video 1
Video 1           Video 2
V      I     D    E    O   1
```

**How to do this**
* Scale and crop the video to fit multiple monitors
    *  Example: 4K video `3840x2160` is cropped to fit two monitors total `3840x1080px` in center to avoid video from being stretched
* Pick individual videos for different monitors (ex. `Video1 on Monitor1` and `Video 2 on Monitor 2`

One of these options would totally work. It would be really cool to add this to Hidamari, super well designed!

**Comment by E-Bachman** [comment]
I found a way to make it work.

* Create a virtual display output in linux using `xrandr`
* Set it as default in `xorg.conf`

Depends on what distro and graphics you use but it works.

**Comment by jeffshee** [comment]
@E-Bachman Does it have any downside with that method you described?
Given the example you mentioned above:
```
display0           display1
1920x1080     1920x1080
Video 1           Video 1
Video 1           Video 2
V      I     D    E    O   1
```
I suppose you successfully achieve the last scenarios, am I right?

For that, if you want an easier hack, check the `_detect_monitor()` function in my script.
Basically, this function looks for the default screen's resolution.
Let's say, you have two 1080p monitors side-by-side, you can manually calculate the combined resolution.
In this case, it should be 3804x1080.
Then you can override `_detect_monitor()` so that it returns the combined resolution.

Of course, if your method did work perfectly, then it's fine too!
I will try to provide such a feature in the future! 😄
