### ISSUE TITLE
No switch desktop animation on GNOME 40

### ISSUE THREAD

**Issue by c3n21** [jeffshee/hidamari#32]
Hello,
when hidamari is running and I switch virtual desktop, switching animations are [cut off](https://gfycat.com/terriblesilkyhammerheadshark).

I'm running Wayland with NVIDIA on a laptop: on Xorg this problem persists.

**Comment by jeffshee** [comment]
Hi @c3n21,
thanks for reporting the issue. Unfortunately, it is a regression in gnome-shell (since GNOME 40) itself.
I had reported this issue to the gnome-shell months ago, which you can refer to here:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4286
It affects some other apps as well, including DING extension and conky.

Sorry that I couldn't provide a fix to this issue atm.
Nice Hu Tao wallpaper there btw. She is also my fav. ;-)
