### ISSUE TITLE
wallpaper not showing on overview

### ISSUE THREAD

**Issue by apoleon33** [jeffshee/hidamari#33]
as said in the title

idk if its normal but when you overview it show a black background instead of the actual wallpaper.

Im on gnome 40 and on manjaro

**Comment by jeffshee** [comment]
Hi @apoleon33 
In that case, probably your video starts from a black frame, isn't it? Hidamari grabs the first frame of the video and sets it as GNOME wallpaper. You can disable this by unchecking the "Apply static wallpaper" option. Then your actual GNOME wallpaper will be shown instead.

Hope it helps. :-)

**Comment by apoleon33** [comment]
hello @jeffshee,
actually my video does not start by a black frame ( I checked by myself). So idk why it was all black (maybe an extension?).
Anyway like you said I unchecked the "apply static wallpaper" option, and made my wallpaper the first frame of the video, ^^

thx for your help

Since the problem is still not fixed, do I let this issue open?

**Comment by jeffshee** [comment]
For now, I'm not sure what is the actual cause of the issue you had mentioned. Since you said you can fix the problem somehow by reloading gnome-shell, I'm guessing the problem is on the gnome-shell side, not on Hidamari. 
>Since the problem is still not fixed, do I let this issue open?

You can keep this issue open. It will be easier for me to check. However, if this issue cannot be reproduced, it will be closed once the next update is released.  If the next update does not resolve the issue, please feel free to reopen this issue.
