### ISSUE TITLE
Crash applying new local video

### ISSUE THREAD

**Issue by c3n21** [jeffshee/hidamari#35]
When applying new local video hidamari crashes.

This is the stacktrace

```
malloc(): unaligned tcache chunk detected
Traceback (most recent call last):
  File "/home/nezuko/Downloads/github/hidamari.git/main/src/gui.py", line 118, in on_local_video_apply
    self.server.video(self.local_video_list[index])
  File "/usr/lib/python3.9/site-packages/pydbus/proxy_method.py", line 72, in __call__
    ret = instance._bus.con.call_sync(
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)
```
[Sample video](https://gfycat.com/linearkeenisabellineshrike)
PS: in the video I'm using the main branch of my repo, which is up to date with the master branch.

**Comment by jeffshee** [comment]
Hi @c3n21 
It is the first time I had seen this kind of error message. It seems the background service `server.py` wasn't responsive for some reason... 
Some questions:
1. How much is the reproducibility of this issue? Does it occur randomly/to any video?
2. Is this issue only occur if the video was just copied to the folder recently?
Some weird things I had noticed:
1. `get_buffer() failed` message, definitely doesn't seem right, and could be the cause of this issue. It could be some codec issue. If so, you could try reencoding your video in h264 instead of the original vp9 using FFmpeg.
2. The thumbnail seems doesn't work in your system, but this should be OK.

**Comment by c3n21** [comment]
> Hi @c3n21 It is the first time I had seen this kind of error message. It seems the background service `server.py` wasn't responsive for some reason...
> 
> Some questions:
> 
>     1. How much is the reproducibility of this issue? Does it occur randomly/to any video?
> 
>     2. Is this issue only occur if the video was just copied to the folder recently?
> 
> 
> Some weird things I had noticed:
> 
>     1. `get_buffer() failed` message, definitely doesn't seem right, and could be the cause of this issue. It could be some codec issue. If so, you could try reencoding your video in h264 instead of the original vp9 using FFmpeg.
> 
>     2. The thumbnail seems doesn't work in your system, but this should be OK.

I usually download my videos from YouTube using `youtube-dl <video url>`.

Right now I'm trying again and it seems that this issue is gone.
