### ISSUE TITLE
[question] does it work with wayland

### ISSUE THREAD

**Issue by fikrillah** [jeffshee/hidamari#4]
From what I read from xwinwrap blog post in the readme file, it is said that xwinwrap only works on xorg. That makes me wonder if hidmari could work on wayland considering there's guide for fedora which use wayland as default. 

Please clarify this, maybe add to the readme file

Thanks

**Comment by jeffshee** [comment]
Nope, it won't work with Wayland as well. It is the limitation of Wayland itself. You have to use Xorg.
In fact, Hidamari does check the session and will pop up an error dialog box when Wayland is detected.
I will make this clearer by adding to the readme file later.

BTW, [https://github.com/chrisss404/gnome-shell-ext-VideoWallpaper](this method) should theoretically work on Wayland since it extends the GNOME shell directly. Maybe someone who has experience with the GNOME extension could work for it.

Thanks.

**Comment by jeffshee** [comment]
@fikrillah Hi, it works now! Please give it a try ;-)
