### ISSUE TITLE
the .config

### ISSUE THREAD

**Issue by osafaimal** [jeffshee/hidamari#41]
hello, i want to launch hidamari without have to select my wallpaper at each start. i have see there is a .config, i don t know what put in "mode" and i am not sure what put in "data source" i think the url or the absolute link to the file, can someone help me please?
thanks in advance

**Comment by jeffshee** [comment]
Due to a bug (https://github.com/jeffshee/hidamari/issues/17#issuecomment-869207534), I know it might sound weird but you might want to "quit hidamari" for the first time after you select the wallpaper. Hopefully, it will trigger the save function.

As for "mode" and "data_source" if you want to try editing the config file instead, it should be "MODE_VIDEO" for video wallpaper and the absolute path to the video, respectively.

**Comment by jeffshee** [comment]
Closed as the new release is out. Feel free to reopen if the issue still remains.
