### ISSUE TITLE
Noticeable lag when moving windows

### ISSUE THREAD

**Issue by nickheyer** [jeffshee/hidamari#66]
OS: Pop!_OS 22.04 LTS
CPU: 12th Gen Intel Core i9-12900k
GPU: RTX 3080Ti
RAM: 32GB DDR5
Monitors: 1 1920x1080 (Portrait) + 3440x1440 Ultrawide screen

After installing and displaying a webpage (ex: https://heyer.app), moving a window (the app's interface or a web browser, file browser, anything) results in noticeable lag. Testing sites like reddit, google, youtube do not produce this lag. 

After testing further, it seems as though websites with animation cause this issue. For example, here is a codepen submission (https://cdpn.io/Wujek_Greg/fullpage/KRXYpg), and this seems to be the case for others as well. 

I hope this is fixed, because Linux's options for dynamic wallpapers are terrible at the moment.

**Comment by jeffshee** [comment]
@nickheyer Hi, thanks for reporting.

It could be an issue with WebKitGTK. Could you please check the mentioned website with [Epiphany](https://flathub.org/apps/details/org.gnome.Epiphany) as well? (which is also using WebKitGTK for HTML rendering)

If Epiphany also have the same issue (laggy/not render properly), I recommend filing a bug report to Epiphany/WebKitGTK, since it’s out of my control unfortunately.

**Comment by nickheyer** [comment]
Can confirm that Epiphany causes the same lag. I'll submit that bug report.

**Comment by nickheyer** [comment]
From a Gnome Web dev on reddit:
"You can probably fix it by setting the WEBKIT_FORCE_COMPOSITING_MODE=1 environment variable, but beware it's off by default for a reason: it will cause your memory use to balloon. A total rewrite of the WebKit graphics stack is needed to fix this unfortunately. Not sure what's happening there currently."
