### ISSUE TITLE
Ultra wide support?

### ISSUE THREAD

**Issue by AngelBrielez** [jeffshee/hidamari#67]
Hi! I would like to know if there is a way to extend the background or if there is a way to implement different types of appearance. Because apparently it doesn't look complete on my ultra wide monitor. u.u

![imagen](https://user-images.githubusercontent.com/39037416/189486999-3a898d2c-7b6e-48f9-8579-6fbc020e17bd.png)

**Comment by jeffshee** [comment]
Hi @AngelBrielez ,

Soon. I'm now implementing it. =3
Yae's head might be cut off if "crop to fit" (center crop) is applied to your video tho. 😏

**Comment by AngelBrielez** [comment]
Ohh, great for the implementation. I'm going to wait for it to be ready, thanks for creating this software, it was already needed in our DE: GNOME. it has a good future :3

**Comment by jeffshee** [comment]
While not mentioned in the changelog, a simple center-crop feature is included in the upcoming update. 
It should be available on Flathub a few hours later 😎

I called it "simple" because we still don't have an interface to control the X and Y offsets, yet.
I'll implement some sort of per-video offset function in the future. (maybe™)

**Comment by AngelBrielez** [comment]
¡Wow! Thanks  @jeffshee Because of your great work, I can now enjoy the animated backgrounds in Gnome 40 :D, on my ultra-wide screen. Here's a coffee on me for your fast support.
![image](https://user-images.githubusercontent.com/39037416/192077377-b6a73b37-ce35-4502-83ac-93c2d8320abf.png)
