### ISSUE TITLE
Hidamari(日溜まり) doesn't mean Sunflower.

### ISSUE THREAD

**Issue by oyajun** [jeffshee/hidamari#82]
Hidamari(日溜まり) means "Sunny Spot". 🌞
Japanese people usually writes 日だまり more than 日溜まり. 
Sunflower calls Himawari (ひまわり) in Japan. 🌻

**Comment by jeffshee** [comment]
Hi @oyajun 

Thanks for your input. Actually… I know Japanese!
Since it’s a good opportunity, let me explain why this project is called Hidamari. 😆

So, just in case you don’t know, there is an app called Komorebi before Hidamari that also do live wallpaper stuff. 木漏れ日 was such a beautiful Japanese word.

To show respect to Komorebi’s work, I decided to name my project with something related to the sun/sunlight. That’s why ひだまり was chosen.
(Btw, ひまわり and ひなた was also the candidates. It was a hard choice tbh.) 

About the Kanji in README, 日溜まり or 日だまり or even 陽だまり, I didn’t care much because all of them is correct. I simply chose the one I liked the most. That said, users shouldn’t be bother because I don’t use any Japanese character as my app’s title. Everyone call it “Hidamari”, easy.

So, if the app is called “Hidamari”, why I use the sunflower for the app icon/git commit message??? The reason is quite simple. (1) I don’t like the 🌞 emoji and the 🌻 is way more adorable. (2) I don’t want to use the sun as app icon just because it will make the app seems like a weather app…

That’s all! Thanks for bringing this to the issue and I hope that users who want to know some “background story” could get the answer here~ 😉
長文失礼しました〜

**Comment by oyajun** [comment]
Hi! @jeffshee.
Thank you.
I am happy to know why this app name is Hidamari.
I think Hidamari is beautiful Japanese.
This app feature is so good! I will use it. Thank you for making this App.
